site_name: ${{values.name | dump}}
site_description: ${{values.description | dump}}
repo_url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
edit_uri: edit/main/docs

nav:
  - Introduction: index.md

plugins:
  - techdocs-core